---
title: "Extra Credit Participation as of 11/11/22"
output: pdf_document
---

Here is a list of the students who participated in the extra credit survey broken down by course section. 
The students on this list are the ones who actually completed the survey and have not just clicked through to the end of the survey without answering anything. 
As a reminder, the students should recieve 5 extra credit points towards their homework grade. 

| **Course section** | **Students' Initials** |
| :----------------- | :--------------------- |
| 940:101:01         | JC                     |
| 940:101:91         | AR                     |
| 940:101:92         | KB, SM, SC, VS, PV, OM, AP |
| 940:102:90         | YX                     |
| 940:121:01         | AS, HR, FJ, PR, EG, XM, MK, JS, JJ, JR, ME, MV, KS |
| 940:121:02         | CN, HT, CF             |
| 940:131:01         | AS, KR, AB, SP, AD, AS, HF, JK, RP, PV, SP, IH, SP |
| 940:131:02         | TA, SA                 |
| 940:131:03         | TD, AP, AP, SJ, EP, NK, RP, JY, SJ, LB, AP, JW, CHM, IL |
| 940:131:90         | JS, TB                 |
| 940:132:01         | MG, AR, JS, CC, IA, JE, RS, BE |
| 940:132:90         | ZJ, KD, FH, GF, NA, LL, DB, VG, AD, AK, MH, ML, AG, JJ, GE |
| 940:132:91         | AH, AT, WS, AD, VU     |


They were also instructed to take a screenshot of the ending screen to send to their instructors. 
I will send an updated list on the last day of classes.
If you have any questions, let me know. 

